version: '3'
services: 
  go_blog:
    build: 
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "go run ./main.go"
    stdin_open: true
    tty: true
    volumes: 
      - .:/GO
    ports: 
      - 8022:8022
    depends_on: 
      - dbblog
  
  dbblog:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_blog
      TZ: 'Asia/Tokyo'
    volumes: 
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/initdb.d:/docker-entrypoint-initdb.d
      - ./database/logs:/var/log/mysql
    ports: 
      - 3336:3306
    